feature_full_names = {"school": "student's school",
                      "sex": "student's sex",
                      "age": "student's age",
                      "address": "student's home address type",
                      "famsize": "family size",
                      "Pstatus": "parent's cohabitation status",
                      "Medu": "mother's education",
                      "Fedu": "father's education",
                      "Mjob": "mother's job",
                      "Fjob": "father's job",
                      "reason": "reason to choose this school",
                      "guardian": "student's guardian",
                      "traveltime": "home to school travel time",
                      "studytime": "weekly study time",
                      "failures": "number of past class failures",
                      "schoolsup": "extra educational support",
                      "famsup": "family educational support",
                      "paid": "extra paid classes within the course subject",
                      "activities": "extra-curricular activities",
                      "nursery": "attended nursery school",
                      "higher": "wants to take higher education",
                      "internet": "Internet access at home",
                      "romantic": "with a romantic relationship",
                      "famrel": "quality of family relationships",
                      "freetime": "free time after school",
                      "goout": "going out with friends",
                      "Dalc": "workday alcohol consumption",
                      "Walc": "weekend alcohol consumption",
                      "health": "current health status",
                      "absences": "number of school absences",
                      "passed": "did the student pass the final exam"}

